name: proxycloud
description: "A modern, feature-rich VPN client that's fast, unlimited, secure, and completely free."
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter_v2ray_client:
    path: local_packages/flutter_v2ray_client
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.2
  flutter_spinkit: ^5.2.0
  clipboard: ^0.1.3
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a2332"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
